### ISSUE TITLE
Generating @context-files

### ISSUE THREAD

**Issue by Blobonat** [FIWARE/tutorials.Understanding-At-Context#7]
Hi,

is there a default way for generating `@context`-files  based on customized Smart Data Models? The `context-file-generator` used in this tutorial seems to be based on @jason-fox [swagger-datamodel-test tool](https://github.com/jason-fox/swagger-datamodel-test). 
Will this tool generate NGSI-LD v1.4.1 conform files?

**Comment by albertoabellagarcia** [comment]
There are two services available on the front page of the [smart data models home page](https://smartdatamodels.org).
Main -> tools ->[ Subjects @context merger](https://smartdatamodels.org/index.php/generate-a-local-context-based-on-smart-data-models-iris/)
In this first service you will be able to merge several subjects' @contexts and the outcome will include all the non-repeated terms in a @context object and the collisions in a **conflicts** object.  
The second service allows you to map the terms of a **@context** against some ontologies (the list of available ontologies in the [data-models repository](https://github.com/smart-data-models/data-models) is [here](https://github.com/smart-data-models/data-models/tree/master/context/ontologies_files)) 
The second service is also available on the front page of the [smart data models home page](https://smartdatamodels.org).
Main -> tools ->[ Mapper @context with external ontologies ](https://smartdatamodels.org/index.php/generate-acontext-based-on-external-ontologies-iris/)

I hope it helps. If you have further questions use [this service](https://calendly.com/smartdatamodels) to book a live support session. The link is in the blue header of [smart data models front page](https://smartdatamodels.org).

**Comment by Blobonat** [comment]
@albertoabellagarcia thanks for the links. Somehow I completely overlooked the "Tools" menu on the Smart Data Model website. I will have a look at it.

**Comment by albertoabellagarcia** [comment]
We will appreciate the feedback on the tools if we can improve them please let us know.
