### ISSUE TITLE
Broken link to FIWARE data models

### ISSUE THREAD

**Issue by max-thoma** [FIWARE/tutorials.Understanding-At-Context#9]
In the "Understanding At Context Tutorial" there is the following statement:

> If a computer encounters an entity of `type=Building` this really refers to a `https://uri.fiware.org/ns/data-models#Building`

The link `https://uri.fiware.org/ns/data-models#Building` seems to be broken for me.
However, changing `data-models` to `dataModels` makes the link work.
Is it possible that the correct link should be `https://uri.fiware.org/ns/dataModels#Building` or am I missing something?

With kind regards
Max

**Comment by jason-fox** [comment]
That is a URN, not a URL. It just so happens that a lot of URNs do actually link to a page on the web, but it isn't always the case. Indeed the core `@context` includes some URNs which do not resolve. This is not an error, merely a consequence of the naming convention being used by the data model.
